# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPeticion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instancia', models.CharField(max_length=150)),
                ('usuario_nombre', models.CharField(max_length=150)),
                ('usuario_pk', models.IntegerField()),
                ('url', models.TextField()),
                ('tipo_peticion', models.CharField(max_length=10)),
                ('codigo_peticion', models.IntegerField()),
                ('tiempo', models.FloatField(default=0)),
                ('informacion', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Registro de peticiones',
            },
        ),
    ]
