# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registropeticion',
            old_name='html',
            new_name='errores',
        ),
    ]
