# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170704_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropeticion',
            name='importante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registropeticion',
            name='solucionado',
            field=models.BooleanField(default=False),
        ),
    ]
